FROM quay.io/fedora/fedora@sha256:89ddd9c1d773dce402e590b3e8b267d30443cb8666afaee278f27e7084685665 AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install \
    awk \
    dnf-plugins-core \
    efivar-devel \
    efivar-libs \
    git \
    nc \
    python3-PyMySQL \
    python3-jinja2 \
    python3-psycopg2 \
    tpm2-tools
