FROM quay.io/fedora/fedora@sha256:2dbff2069a45080720c8ea04862ca0c7f3fd202c090baf7372755a424ef1449c AS keylime_base
LABEL version="_version_" description="Keylime Base - Only used as an base image for derived packages"
MAINTAINER Keylime Team <main@keylime.groups.io>

RUN dnf -y install dnf-plugins-core git efivar-libs efivar-devel python3-jinja2 python3-PyMySQL python3-psycopg2 nc && dnf -y builddep tpm2-tools
RUN git clone -b 5.7 https://github.com/tpm2-software/tpm2-tools.git && \
    cd tpm2-tools && \
    git config user.email "main@keylime.groups.io" && \
    git config user.name "Keylime" && \
    ./bootstrap && \
    ./configure && \
    make && make install && \
    cd .. && rm -rf tpm2-tools
